# Generated by Django 5.1.4 on 2024-12-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_post_options_news_post_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_post',
            old_name='autor',
            new_name='author',
        ),
    ]
